version: 2.0

job_steps: &job_steps
  - checkout
  - restore_cache:
      key: v1-bundle-{{ checksum "Gemfile.lock" }}
  - run: bundle install --path vendor/bundle
  - run:
      name: Run tests
      command: bin/testunit
  - save_cache:
      key: v1-bundle-{{ checksum "Gemfile.lock" }}
      paths:
        - vendor/bundle

jobs:
  linux:
    docker:
      - image: circleci/ruby:2.3-node
    steps: *job_steps
  mac:
    macos:
      xcode: "10.2.0"
    steps: *job_steps
      
workflows:
  version: 2
  build_and_test:
    jobs:
      - linux
      - mac
